version: 1.0.{build}
clone_depth: 1
clone_folder: C:\projects\inexor-game

platform: 
  - Win32
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
#  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# scripts that run after cloning repository
install:
  - cmd: cd C:\projects\inexor-game
  - cmd: git submodule update --init

# scripts to run before build
before_build:
  - cmd: cd C:\projects\inexor-game
  - cmd: md build
  - cmd: cd build
  # We generate project files for Visual Studio 13 only atm.
  - cmd: if "%platform%"=="Win32" set "CMAKE_GENERATOR_NAME=Visual Studio 12 2013"
  - cmd: if "%platform%"=="x64"   set "CMAKE_GENERATOR_NAME=Visual Studio 12 2013 Win64"
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: C:\projects\inexor-game\build\inexor.sln

  # enable MSBuild parallel builds
  parallel: true

  # MSBuild verbosity level (quiet|minimal|normal|detailed)
  verbosity: normal

on_success: #we atm do not use it as test_script: bc if it fails then it signals a failed build
  - cmd: cd C:\projects\inexor-game\
  # We (probably) need to install the solution first
  - cmd: MSBuild build\install.vcxproj /t:build
  # run the test executable
  - cmd: if "%platform%"=="Win32" set "inexor_platform_name=win32"
  - cmd: if "%platform%"=="x64"   set "inexor_platform_name=win64"
  - cmd: tool\appveyor-workaround.bat
